### ISSUE TITLE
SSL handshake fails because IP SANs are missing

### ISSUE THREAD

**Issue by soupdiver** [elastic/logstash-forwarder#221]
I've used the command from the README for generating a SSL certificate. I use the same cert on the server and on the forwarder. When starting the forwarder I get the following error:
```
Failed to tls handshake with x.x.x.x x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs
```

So I see it is a problem with the cert and not the forwarder itself but maybe you can update the README.

**Comment by josh-padnick** [comment]
First, special thanks to @driskell for the great script.  Worked like a charm.  

Second, I also ran into the error message: `x509: certificate is valid for , not logstash.mydomain.com`, but I was able to fix it once I updated not only the `.crt` file for logstash-forwarder, but also the one for the logstash server in `/etc/pki/tls/certs/logstash-forwarder.crt`.

Once I updated that cert, it works great.

**Comment by swapnil-jaiswal** [comment]
Hi. 
I am new to Logstash-forwarder, i have downloaded the script lc-tlscert.
Compiled the script and logstash-forwarder via the latest version of go ( /usr/bin/go version
go version go1.4.1 linux/amd64)

Version of other softwares in stack :
OpenSSL 1.0.1e-fips 11 Feb 2013

lumberjack code - via git hub v0.3.1.

On starting lumberjack i am getting following error.

2015/01/28 12:34:24.292164 Connecting to [172.31.22.235]:5043 (logstash.compute.internal)
2015/01/28 12:34:24.312255 Failed to tls handshake with 172.31.22.235 x509: certificate signed by unknown authority
2015/01/28 12:34:25.312763 Connecting to [127.0.0.1]:5043 (logstash.compute.internal)
2015/01/28 12:34:25.317503 Failed to tls handshake with 127.0.0.1 x509: certificate signed by unknown authority
2015/01/28 12:34:26.317956 Connecting to [172.31.22.235]:5043 (logstash.compute.internal)
2015/01/28 12:34:26.323748 Failed to tls handshake with 172.31.22.235 x509: certificate signed by unknown authority
2015/01/28 12:34:27.324190 Connecting to [127.0.0.1]:5043 (logstash.compute.internal)
2015/01/28 12:34:27.329292 Failed to tls handshake with 127.0.0.1 x509: certificate signed by unknown authority
2015/01/28 12:34:28.329783 Connecting to [172.31.22.235]:5043 (logstash.compute.internal)
####

Am I missing something obvious ?

**Comment by swapnil-jaiswal** [comment]
I appended the certificate to the wrong file 
openssl x509 -text -in  logstash-forwarder.crt  >> ca-bundle.crt

did the trick :)

**Comment by larryzhao** [comment]
Hi @jordansissel , I followed your guide in https://github.com/elasticsearch/logstash-forwarder/issues/221#issuecomment-48390920 , the `IP SANs` problem went away, but now I get: `Failed to tls handshake with <server ip> x509: certificate signed by unknown authority`.

Is there anything else that I need to tweak?

Thanks a lot.
Larry

**Comment by grahamrhay** [comment]
"If you don't need security, I highly recommend using any other transport tool"

@jordansissel, can you recommend an alternative, other than the default logstash client? I'd prefer to avoid installing the JVM, as our instances are quite small. The log traffic only moves across a private network, we don't have DNS, and adding an IP address as a SAN is quite painful as it can change at any time (no elastic IPs).

**Comment by driskell** [comment]
@grahamrhay I maintain [Log Courier](https://github.com/driskell/log-courier) which supports pure TCP only transport.

**Comment by grahamrhay** [comment]
@driskell I'll take a look, thanks

**Comment by Neetuj** [comment]
My issue is the logstash forwarder is complaning to connect to logstash server 
   2015/02/26 16:31:36.301402 Setting trusted CA from file: /opt/logstash-forwarder/ssl/logstash-  forwarder.crt
   2015/02/26 16:31:36.301781 Connecting to [16.x.x.x.x]:5000 (168.1.85.75) 
   2015/02/26 16:31:36.307869 Failed to tls handshake with 168.x.x.x.: cannot validate certificate for x.x.x.x  because it doesn't contain any IP SANs

I downloaded the go script 
    wget https://github.com/driskell/log-courier/blob/develop/src/lc-tlscert/lc-tlscert.go
When i build it i get errors
   go build lc-tlscert.go
   can't load package: 
   lc-tlscert.go:4:1: expected 'package', found '<'
   lc-tlscert.go:7:19: illegal character literal


any pointers?

**Comment by kiranos** [comment]
@Neetuj https://github.com/elasticsearch/logstash-forwarder/pull/319 this might help you

**Comment by driskell** [comment]
@neetuj You downloaded the github page instead of the file. Get the file via whet from here:
`wget https://raw.githubusercontent.com/driskell/log-courier/develop/src/lc-tlscert/lc-tlscert.go`

**Comment by Neetuj** [comment]
thanks .. i build that .. and restarted logtstash and forwarder ..but now i am nto abel to connect to the server

did i miss anything ? (port and ip are correct)
2015/02/26 19:13:26.268676 Connecting to [168.1.85.75]:5000 (168.1.85.75) 
2015/02/26 19:13:26.270045 Failure connecting to 1.x.x.: dial tcp 1.x.x.x:5000: connection refused

**Comment by gebi** [comment]
Why not just document, that user should pick a hostname for the certificate and not an IP?
No fancy special cert generator needed.

Btw... the command to generate the certificates for logstash-forwarder from the documentation is wrong and does not produce usable certificates (they lack a DN in the default debian config of openssl) #399 
The fix is to remove `--batch` from the sample openssl command and just use the hostname to connect (where hostname needs to be the DN in the certificate) and be done.

**Comment by NuSkooler** [comment]
As @gebi stated, I think some slight documentation love would go very far. I wasted a few hours with this yesterday. The simple fix is to use a hostname and supply -subj /CN=said-hostname. This works in simple test environments as well as long as the logstash-forwarder knows of the host (e.g. put in in /etc/hosts).

**Comment by jordansissel** [comment]
@NuSkooler the README for this project already contains `-subj /CN=hostname`.

**Comment by jordansissel** [comment]
> the command to generate the certificates for logstash-forwarder from the documentation is wrong

If I copy/paste what the README has, it works in both OSX and Ubuntu 12.04. I don't know how your own system is configured (Debian?) to cause failure. I do not have any experience with Debian or its choices of openssl configuration.

```
% openssl req -x509  -batch -nodes -newkey rsa:2048 -keyout lumberjack.key -out lumberjack.crt -subj /CN=logstash.example.com  > /dev/null 2>&1; openssl x509 -text -in lumberjack.crt | grep CN
        Issuer: CN=logstash.example.com
        Subject: CN=logstash.example.com
```

**Comment by NuSkooler** [comment]
@jordansissel: The important bit (besides providing CN=) that I believe could use some empesis in the documentation: Always utilize a hostname. Using a IP address, while doable, is a real pain.

**Comment by jordansissel** [comment]
@NuSkooler complete agreement there.  How about this change? https://github.com/elasticsearch/logstash-forwarder/pull/409/files

**Comment by NuSkooler** [comment]
@jordansissel: I think that should help!

**Comment by martinb3** [comment]
Is there any option for an explicit trust model for these x.509 certificates? Or is the PKI trust model (that verifies fields like CN) the only option with Go 1.3.x and greater? Some of us don't need to verify the host on the other end; we already have a mechanism for ensuring that. We just want the encryption functionality.

**Comment by jordansissel** [comment]
@martinb3 There is no way I know of in Go, no. The Go developers seem to have chosen a dichotomy of "no validation at all" or "certificate AND subject validation". You cannot do just certificate trusts anymore. It is quite frustrating. Sorry for that :(

**Comment by martinb3** [comment]
@jordansissel thanks for the update; that's disappointing about Go, but I appreciate your efforts!!

**Comment by driskell** [comment]
https://groups.google.com/forum/#!topic/golang-nuts/4vnt7NdLvVU
Seems to be a method here - disabling both checks and then performing just the certificate check yourself. opts would need to have Roots member changed to just the configured certificate root.

**Comment by jimmod** [comment]
@driskell 
Thank you for the lc-tlscert.go
I success using lc-tlscert on cloud environment with DNS
But when I tried to setup local testing environment without DNS, only IP, logstash forwarder error 

>Failed to tls handshake with x.x.x.x x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs

Got any hint?

**Comment by driskell** [comment]
@jimmod Make sure you include the IP address in the SANs when running lc-tlscert and not common name. Never put the IP in the common name - always make up a DNS if you don't have one. Then IP always should go in the SAN. I'll make an update soon to make this clear in the instructions lc-tlscert gives.

**Comment by gebi** [comment]
@jimmod use DNS and add the records to /etc/hosts file of your local test machine, no special tool needed (the openssl command from README works just fine)

**Comment by jimmod** [comment]
@driskell ok it work now.
I found some error in the logstash configuration (my bad).
And confirm it work with IP or DNS via /etc/hosts file.
Thank you

**Comment by SJ04** [comment]
Hi there!!

I read this whole thread but it i still have the same Failed to tls handsake Error.
I used this command to create a Cert. 

 openssl req -x509  -batch -nodes -newkey rsa:2048 -keyout lumberjack.key -out lumberjack.crt -subj /CN=logstash.example.com

Just got a little Confusion about the CN, Should it be the Host Logstash Server or Client.

**Comment by RiaanPretorius** [comment]
Seems the main issue here is SSL does not work. And you can not disable it either. So no logstash-forwarder

**Comment by driskell** [comment]
@riaanpretorius It does work - it's just easy to setup wrong. In every case I've helped we've found the problem and fixed it. If you'd like to share your config and steps followed there'll be someone happy to help I'm sure.

If you want without SSL there are alternatives available: beaver, nxlog, log-courier (which I maintain) I think all support plain tcp

**Comment by RiaanPretorius** [comment]
@driskell Ifollowed the guides i found on internet e.g. https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-4-on-ubuntu-14-04  and https://github.com/elastic/logstash-forwarder#generating-an-ssl-certificate and a lot more. My biggest problem is multiple domains, sub domains. Plain TCP would be welcomed. 

I would gladly share my configs, but also keep in mind i followed the conversaion from start to end and nothing worked. 

I am going try log-courier it seems to best option.

**Comment by ashwgupt** [comment]
All of the alternatives to logstash-forwarder look good but it still appears to me that none come with as easy and simple integration with Logstash as the forwarder - No plugin or extra installations on Logstash server side, no other dependencies, and ease to use config file. Please correct me if wrong.

Hence, I am very keen to make my forwarder work out but not able to due to the ssl handshake issue.

Can any one suggest what are the possible reasons for my forwarder (on RHEL 6) not able to work with my Logstash server cert file and throwing the below error?

2015/06/07 15:47:23.964418 Setting trusted CA from file: /usr/bin/mw_lumberjack.crt
2015/06/07 15:47:23.966107 Connecting to [10.51.167.10]:10010 (ukx01234.ab.dc-intl.com)
2015/06/07 15:47:23.971762 Failed to tls handshake with 10.51.167.10 x509: certificate is valid for , not ukx01234.ab.dc-intl.com

Pasting the config and cert details below.

Cert Issuer:-
Signature Algorithm: sha1WithRSAEncryption
        Issuer: CN=*.ab.dc-intl.com
        Validity
            Not Before: Jun  5 12:24:20 2015 GMT
            Not After : Jun  4 12:24:20 2016 GMT
        Subject: CN=*.ab.dc-intl.com

Forwarder Config File:-
# The network section covers network configuration :)
  "network": {
    # A list of downstream servers listening for our messages.
    # logstash-forwarder will pick one at random and only switch if
    # the selected one appears to be dead or unresponsive
    "servers": [ "ukx01234.ab.dc-intl.com:10010" ],

    # The path to your client ssl certificate (optional)
    ##"ssl certificate": "./logstash-forwarder.crt",
    # The path to your client ssl key (optional)
    ##"ssl key": "./logstash-forwarder.key",

    # The path to your trusted ssl CA file. This is used
    # to authenticate your downstream server.
    "ssl ca": "/usr/bin/mw_lumberjack.crt", 

I've already tried other options of mentioning the issuer's FQDN differently in the cert but NO luck.

I also understand GO can be used to create new set of certs but my first concern is that the instructions provided in forwarder's documentation should work for me unless am making a mistake or there is a technical issue.

**Comment by quickwind** [comment]
I am still wondering why not giving the option to turn off SSL, all the solutions so far are not ok for your deployment, we are using Docker for our micro-services, and we would like each container (per service instance) will have a logstash-forwarder to forward the logs to a centralized logstash shipper (also in Docker container) in the same host, these Docker containers are using bridge mode (NAT), there is not easy way for us to generate SSL cert in my understanding, as the IP address is dynamic, Docker container itself is not in domain, hostname is dynamic as well (although we can fix it by specifying the hostname for the logstash-shipper container and linking it to the fowarder containers, but still is it a valid option here as we only have /etc/hosts covered but not under any domain?). 

I hate not having choices, it is like in China....

**Comment by tymik** [comment]
I was reading through the comments and what I see is that there is a need to update README file and manual on page in point that stands for genering certs - it is not mentioned there, that there is a need to set valid address in config file for ssl, where it should be mentioned and explained, what address (fqdn or num IP) should be used. So this is the first place, where the "bug" should get fixed.

**Comment by jdleehuit** [comment]
I've tried to resolve this issue by regenerating the cert and key every which way and I am still getting the handshake issue:

Failed to tls handshake with x.x.x.x x509: cannot validate certificate for x.x.x.x because it doesn't contain any IP SANs

I've tried the following open ssl commands:

openssl req -config /etc/pki/tls/openssl.cnf -x509 -days 3650 -nodes -newkey rsa:2048 -keyout /etc/pki/tls/private/logstash-forwarder.key -out /etc/pki/tls/certs/logstash-forwarder.crt

openssl req -x509 -nodes -newkey rsa:2048 -keyout logstash-forwarder.key -out logstash-forwarder.crt

openssl req -subj '/CN=logstash.cloud.xxx.xxx.xxx/' -x509 -days 3650 -batch -nodes -newkey rsa:2048 -keyout private/logstash-forwarder.key -out certs/logstash-forwarder.crt


openssl req -x509  -batch -nodes -newkey rsa:2048 -keyout /etc/pki/tls/logstash-forwarder.key -out /etc/pki/tls/logstash-forwarder.crt -subj /CN=logstash.cloud.xxx.xxx.xxx  > /dev/null 2>&1; openssl x509 -text -in lumberjack.crt | grep CN

When using the DNS CN option I have created an entry in /etc/hosts for the dns name pointing to the logstash server ip. I have also used the lc-tlscert utility for both DNS and IP with no success.

Specify the Common Name for the certificate. The common name
can be anything, but is usually set to the server's primary
DNS name. Even if you plan to connect via IP address you
should specify the DNS name here.

Common name: logstash.cloud.x.x.x.x

The next step is to add any additional DNS names and IP
addresses that clients may use to connect to the server. If
you plan to connect to the server via IP address and not DNS
then you must specify those IP addresses here.
When you are finished, just press enter.

DNS or IP address 1: x.x.x.x
DNS or IP address 2: 

How long should the certificate be valid for? A year (365
days) is usual but requires the certificate to be regenerated
within a year or the certificate will cease working.

Number of days: 365
Common name: logstash.cloud.huit.harvard.edu
DNS SANs:
    None
IP SANs:
    x.x.x.x

The certificate can now be generated
Press any key to begin generating the self-signed certificate.

Successfully generated certificate
    Certificate: selfsigned.crt
    Private Key: selfsigned.key

Copy and paste the following into your Log Courier
configuration, adjusting paths as necessary:
    "transport": "tls",
    "ssl ca":    "path/to/selfsigned.crt",

Copy and paste the following into your LogStash configuration, 
adjusting paths as necessary:
    ssl_certificate => "path/to/selfsigned.crt",
    ssl_key         => "path/to/selfsigned.key",


Any suggestions?

**Comment by driskell** [comment]
@jdleehuit If you use the lc-tlscert method - can you verify the error message? It should be different - if lc-tlscert says it added IP SAN, then the error message shouldn't be because there is no IP SAN. Are you sure the message is not changing between your different tests?

**Comment by driskell** [comment]
Also - when putting the hostname in /etc/hosts and connecting using the hostname it does not make sense that it would mention an IP address in the error message. Can you check again?

**Comment by jdleehuit** [comment]
@driskell Here's the error I get with the lc-tlscert method:

2015/07/08 17:13:58.821467 Connecting to [x.x.x.x]:5000 (logstash.cloud.x.x.x.x) 
2015/07/08 17:13:58.823598 Failed to tls handshake with x.x.x.x x509: certificate is valid for , not logstash.cloud.x.x.x.x

**Comment by jdleehuit** [comment]
@driskell It is working now! Silly error, restarted logstash server after recopying over key and crt and all is well. Thanks for your help!

**Comment by jordansissel** [comment]
Creating SSL certificates is somewhat out of scope for this project. There are tools and documentation for doing this online in various places.

My strongest recommendation is to avoid the difficulty of certificate Subject Alternatives (IP SAN, etc) and just use DNS so you can use a CN=hostname subject. The choice is up to you :)

**Comment by w0www** [comment]
After hours i cant connect to my logstash server with logstash forwarding.

I tried a lot of things.

Now i have a certificate in server. Then i copy the certificate to the client side and i received error signed by unknown agent.

ANY SOLUTION? The server is ubuntu 14.04 and the client is ubuntu 14.04 too. thanks

**Comment by giantninja** [comment]
I've been fighting with this ssl failed to handshake issue for a while now, but finally got it working.  For me the key was what @jordansissel said earlier.  Also, you only need the ssl_sa field pointing to the .crt in the logstash-forwarder config.  Like so:

#### logstash-forwarder.conf
```
{
  "network": {
    "servers": [ "dev.server.com:5043" ],
    "ssl ca": "/opt/logstash-forwarder/lumberjack.crt",

    "timeout": 15
  },
  "files": [
    {
      "paths": [
        "/var/log/php/*.log",
        "/var/log/php-fpm/*.log"
      ],
      "fields": { "type": "lumberjack" }
    }
  ]
}
```

#### logstash.conf
```
input {
  lumberjack {
    port => 5043

    ssl_certificate => "/opt/logstash-forwarder/lumberjack.crt"
    ssl_key => "/opt/logstash-forwarder/lumberjack.key"

    type => "lumberjack"
  }
}
output {
    stdout {}
    elasticsearch {
        cluster => "elasticsearch"
    }
}
```

and this worked for generating the crt/key:

openssl req -x509  -batch -nodes -newkey rsa:2048 -keyout lumberjack.key -out lumberjack.crt -subj /CN=dev.server.com

**Comment by SydOps** [comment]
If we set cluster as *"servers": [ "server1:6782", "server2:6782" ],* in logstash forwarder config file, how can I generate the certificate? 

Do I have to add domain name in the server hostname?

**Comment by brunof399** [comment]
lc-tlscert.go has worked perfectly for my Logstash deployment. However, it appears the certificates are created with SHA 1 hash instead of SHA 2. Is there any modification I can make to lc-tlscert so that the certificates I generate are SHA 2? Thanks!

**Comment by florianajir** [comment]
logstash and filebeat ssl configuration are a lot more strict than elasticsearch or kibana configuration. 
IMO we should have an option to skip hostname verification like in the other products.
This could avoid a lot of headaches

**Comment by vhosakot** [comment]
I saw the same error when using mysql client in golang:

```
Failed to connect to database:  x509: cannot validate certificate for 10.111.202.229 because it doesn't contain any IP SANs
```

and setting `InsecureSkipVerify` to `true` (to skip verification of certificate) resolved it for me:

https://godoc.org/crypto/tls#Config
