### ISSUE TITLE
logstash-forwarder development status

### ISSUE THREAD

**Issue by kosfar** [elastic/logstash-forwarder#259]
Hi all,
we tried ELK stack recently and we are very happy so far. We want to deploy logstash shippers to hunders of machines so for our tests we opted in LSF as it is: 
a. lightweight and simple
b. packaged under elasticsearch repo
c. seems to be developed under the same umbrella that logstash is

Before commiting further on the software, we would like to know the future steps of logstash-forwarder (is it under development, is it abandoned?) and how often the changes in upsteam are embedded on the ES repo package.

That will help us understand if we should take into consideration in-house packaging of another logstash shipper (at the cost of losing on simplicity and taking steps away from the LS ecosystem).

Regards,
Kostis

**Comment by sandstrom** [comment]
Any updates on this? Last release was ~1.5 years ago. LSF is great, I'd love to see releases more often.

**Comment by markwalkom** [comment]
We're working on getting an updated release out in the very near future :)
Don't have a timeframe, but it'll be close to the release of LS 1.5.

**Comment by sandstrom** [comment]
@markwalkom Great to hear! :+1: :boat: 

Except disagreeing on forcing TLS (https://github.com/elasticsearch/logstash-forwarder/issues/226#issuecomment-49002297) I think LSF is awesome.

And despite it's limited roll (shipping logs) I think it's central to make the logs use-case of ELK pleasant, so I'm happy to hear it'll get some love.

To add on this, I understand that you want to take ELK beyond logs (and we already use the stack for other things!). But since log handling is something that most organizations must do I don't think it should be disregarded. Log aggregation is an excellent “gateway-drug” to the rest of the ELK stack :smile:

**Comment by suyograo** [comment]
We released 0.4.0 https://www.elastic.co/blog/logstash-forwarder-0-4-0-released
