### ISSUE TITLE
debian packages quality

### ISSUE THREAD

**Issue by zabbal** [elastic/logstash-forwarder#299]
Having your own repository is fine for development version but I really would like to see it in main debian/ubuntu repo. This, however, would require making decent packages - please have a look on what lint reports for .deb and fix all the warnings and errors. The most obvious thing - binaries do not belong to /opt by any interpretation of FHS.

**Comment by jordansissel** [comment]
Having logstash-forwarder shipped with Debian or Ubuntu, out of the box, or available in the default package repository for those distributions, is *not* something I want.

I'm not having a discussion about FHS. It is a very imprecise standard, nobody really knows what it means, and everyone argues about it. It is a distraction.

> The most obvious thing - binaries do not belong to /opt by any interpretation of FHS.

I don't know how you are interpreting the FHS, but let's say we need to obey the FHS, right?

http://www.pathname.com/fhs/pub/fhs-2.3.html#OPTADDONAPPLICATIONSOFTWAREPACKAGES

Quoting the FHS:

* "/opt : Add-on application software packages"
* "The use of /opt for add-on software is a well-established practice in the UNIX community"

I don't know how you are interpreting this to mean "binaries to not belong in /opt", but I disagree with your assertion. 

That said, FHS is not a meaningful standard because it is imprecise, confusing, and my personal experience is that I have never worked anywhere that followed FHS nor have I used any linux distro that follows FHS in a way that I understand (Gentoo, Arch, Fedora, CentOS, Debian, Ubuntu).

> please have a look on what lint reports for .deb and fix all the warnings and errors

The packages are, to the best of my knowledge, functional and working well. If something isn't working, I would love to know (there can always be bugs I don't know about), and will be happy to help resolve these problems.
