### ISSUE TITLE
PID not recorded

### ISSUE THREAD

**Issue by dlangille** [elastic/logstash-forwarder#333]
It is helpful to have the PID for logstash-fowarder. It is not recorded at present.

/var/run/logstash-forwarder.pid seems to be a logical default location, but configurable.

**Comment by UlrichEckhardt** [comment]
In order to avoid multiple running instances, there is a tool called "flock" that works with any process, so you don't have to reimplement that inside the logstash-forwarder.

If you need a PID file in order to e.g. find and kill the forwarder, there's no need to modify the forwarder either. For example, the following is from a CentOS init.d script, using BASH syntax:
```
 PID=$(runuser -s /bin/sh $USER -c "$EXECUTABLE $LOGSTASH_FORWARDER_OPTIONS >> $STDOUT_LOG 2>&1 & echo \$!")
```

**Comment by deletemeverysoon** [comment]
Most programs manage to do this without using flock.  Why require another tool when it can be done without?

**Comment by UlrichEckhardt** [comment]
Creating tempfiles/lockfiles safely (not exploitable by e.g. symlink attacks) and reliably cleaning them up etc is not trivial. Also, you are not required to have that tool, only if you need the feature it provides and if you want another feature, why not require another tool for it?

**Comment by dlangille** [comment]
Many other programs manage to do so safely.

**Comment by UlrichEckhardt** [comment]
I don't get what you want to express with that statement. I also don't rule out that you don't understand what I wanted to express either. So, let me try again: While it is indeed possible to implement this inside LSF, you don't have to. The complexity of the additional feature and the presence of existing alternatives is for me a good reason not implement this inside LSF. And even if it was a bit better inside LSF, using flock could still be considered a good workaround, which I took the time to describe, so that others looking for solutions to this problem can find it.

**Comment by driskell** [comment]
I'm pretty sure 0.4.0 already has a PID file as it uses pleaserun?

**Comment by jordansissel** [comment]
Thanks for helping make logstash-forwarder better! 

Logstash-forwarder is going away and is replaced by [filebeat](https://github.com/elastic/filebeat/) and its friend, [libbeat](https://github.com/elastic/libbeat/). If this is still an issue, would you mind opening a ticket [there](https://github.com/elastic/libbeat/issues)?
