### ISSUE TITLE
[0.4.0] Error log contains all events (any level)

### ISSUE THREAD

**Issue by svenmueller** [elastic/logstash-forwarder#424]
Seems like all the logged events (info/error) are in the error log (standard log is empty).

```bash
smueller@app1.sphere.cloud.commercetools.de [2015-03-13 17:10:51]:~$ tail -f /var/log/logstash-forwarder/logstash-forwarder.err 
2015/03/13 17:10:14.161532 Registrar: processing 9 events
2015/03/13 17:10:19.162871 Registrar: processing 4 events
2015/03/13 17:10:24.681903 Registrar: processing 1024 events
2015/03/13 17:10:26.682624 Registrar: processing 1024 events
...
```

Any idea why this could be the case?

**Comment by driskell** [comment]
Logstash forwarder prints all diagnostics to STDERR as some other tools do - it produces no usable output so STDOUT is empty. It more of a philosophical issue.

The service script is generated by pleaserun which saves the logs this way. The maintainer did say he might change it so it's not ".err" and ".out" and actually is ".stderr" and ".stdout" which may or may not explain things better.

**Comment by jordansissel** [comment]
@svenmueller I think I need to improve the documentation and expectations. I'll try to clarify, let me know how it helps:

logstash-forwarder has no concept of "info" or "error" logging. Just logs with no categorization. It writes these logs (as @driskell said) to a file descriptor called "standard error". The script we ship with the rpm/deb simply captures both standard out and standard error and writes them to separate files on disk. It is confusing that there is an empty .log file, and I'm going to make this change on the tool that generates it.

**Comment by jordansissel** [comment]
Tracking this concern in #395 (closing this as a duplicate)

**Comment by svenmueller** [comment]
@jordansissel +1 yep, the doc helps to improve the situation. but even more clear would it be, when there is only one file like `.log` ;)

**Comment by jordansissel** [comment]
@svenmueller only one log file is not possible because the init script runs several things (which could produce output) to setup the environment before executing logstash-forwarder. The limitation is in the shell, unfortunately.

Code: https://github.com/jordansissel/pleaserun/blob/master/templates/sysv/lsb-3.1/init.sh#L56-L60

chroot, any ulimit settings, cd, and exec each could have their own output (to stdout or stderr). Normally, they won't, but they could, and we would lose this information if not captured.

I agree one output file would be best, but I'm not sure how to achieve that.

We could redirect both stdout and stderr to a single file, maybe?
