### ISSUE TITLE
Option to pass '.logstash-forwarder' registrar path

### ISSUE THREAD

**Issue by boynux** [elastic/logstash-forwarder#450]
I'm trying to use logstash-forwarder in Docker containers. The problem is registrar puts file references in hardcoded '.logstash-forwarder' in current path in which application has been started. When Docker container get destroyed the registrar file is deleted as well and in next container launch forwarder tries to read all logs from the beginning. 
I wrote a patch that adds an option to app to change file path. Then it's easy to mount a volume and keep those information into host itself.

Before submitting a pull request I'd like to know if there is an easier (existing) solution for this problem.

**Comment by lmorfitt** [comment]
I would also like this as a option please.  +1

**Comment by lmorfitt** [comment]
Additionally this has caused me an issue today. The state file was in /.logstash-forwarder. We have restarted logstash-forwader from /root/ which has created a new file and lost the state of two files which contain a total of 1.6gb of data which now is being reprocessed and duplicated 12 months worth of data in elastic search.

**Comment by lmorfitt** [comment]
Actually my issue is with the older version of LSF 0.32 and has been fixed by 0.40. Please disregard my last comments as they are not valid for the latest version.

**Comment by magnusbaeck** [comment]
Since LSF opens the .logstash-forwarder file in the current directory, can't you change the current directory before starting it?

Related discussion: https://discuss.elastic.co/t/prevent-re-reading-files-from-beginning/25889

**Comment by PMDubuc** [comment]
I would also like to see this option added.  Changing the current directory isn't a good option for me. We run forwarders in a current directory that saves stderr and stdout to files (among others) that are cleaned up when the process is restarted.  Since the .logstash-forwarder file is meant to persist between runs, there should be a way to define it's location elsewhere.  I can do this for the Logstash .sincedb_* files by setting HOME in the environment.  This doesn't work for logstash-forwarder.  Unfortunately it's hard coded to use the current directory.

**Comment by ruflin** [comment]
This will be solved with filebeat. It will be possible to set the filepath + name in the config: https://github.com/elastic/filebeat/pull/10

**Comment by jordansissel** [comment]
@ruflin agreed. https://github.com/elastic/filebeat/pull/10 was merged. I'll close this.
