### ISSUE TITLE
Make SSL optional

### ISSUE THREAD

**Issue by jordansissel** [elastic/logstash-forwarder#5]
some folks don't want or need ssl (nor the overheads of SSL cert management)

**Comment by jonlieb** [comment]
Jordan,
My corporate security measures are not allowing me to access   http://cookbook.logstash.net/recipes/log-shippers/ .
Is there a way that I can view the information?

**Comment by amlwwalker** [comment]
Im struggling with getting logstash to use my certificate. However instead of posting twice and littering the  internet, could anyone have a look at my question here: http://stackoverflow.com/questions/31619000/linux-logstash-forwarder-ssl-ip-sans
I will post the working solution here once I understand what is wrong with my configuration

**Comment by driskell** [comment]
What's your logstash config? The logstash.json you posted was the forwarder config not the logstash config.

Forwarder logs are saying, "the certificate logstash gave me doesn't have any IP SAN" so it's logstash config we should check and the certificate logstash is exposing.

**Comment by autumnw** [comment]
A weird issue for me:
I generated the crt and key following the document. Configured correctly on logstash server and forwarder. Even I remove all the conent in crt file in forwarder side, forwarder still can connect to server successfully. Does this mean actually the ssl cert is useless? My OS is centos6.5/6.6, logstash version is 1.5.2.

**Comment by philomatic** [comment]
+1 for optional ssl support.

However, I can understand your point of view.
For newbies on the ELK stack:

Can you recommend a log shipper from the above which is easy to to configure, secure (in terms of qos level) and has a small footprint on the client?

Best regards

**Comment by driskell** [comment]
SSL has been optional in Log Courier for a long time. And in the upcoming release of Elastic Fillebeat will also be optional.

I generally say keep it enabled. In nearly all cases I've seen just using hostnames and /etc/hosts if needed has solved all problems. Just be careful when you configure logstash-forwarder as if you misspell the configuration it ignores it (courier and filebeat will shout at you though).
It's also important to use SSL to ensure reliable transmission, as TCP can suffer from random corruptions of the data, which may or may not cause problems at the Logstash end or even in Elasticsearch. TCP checksums are in no way sufficient, and SSL adds additional message validation. (http://www.evanjones.ca/tcp-and-ethernet-checksums-fail.html)

**Comment by philomatic** [comment]
In my case (like already mentioned by others above):

How about virtual networks (e.b. VPNs); isn't a additional ssl encryption too much overhead for no real benefits? Hostnames or /etc/hosts aren't my concern here. In big networks theres some kind of hostname resolution anyway.

Thanks anyway for Log Courier, will look into that :)

**Comment by driskell** [comment]
Overhead in my experience is negligible. And generally the VPN only starts from the router so there's still a large area for TCP corruptions to occur. Granted, they'd be extremely rare. I guess what I'm trying to say is - if docs were better and tools were better, and they ARE getting better, the discussion really becomes more and more irrelevant since there's no real disadvantage to using TLS - it becomes merely a protocol point that a user need not worry about.

Until that point though - I'm in agreement with others for the option to disable TLS for those that have problems. But only once they have had problems, so that it may be later improved. If everyone switched to TCP we'd be going backwards! :-)
