### ISSUE TITLE
Make offset field in LSF optional

### ISSUE THREAD

**Issue by ppf2** [elastic/logstash-forwarder#554]
LSF forwarder currently creates an "offset" field for each event generated to store its file byte offset value.    While the offset field can be useful for debugging and identifying potential duplicate events, it is best to make it optional.

**Comment by ruflin** [comment]
logstash-forwarder was replaced by the filebeat project and all further development is going on here: https://github.com/elastic/beats/tree/master/filebeat

Currently it is not possible to disable the offset field. We are working on a filtering implementation which makes it possible to filter out the field: https://github.com/elastic/beats/pull/830 Otherwise you could remove the field on the LS side.

Closing this issue to we can have all further discussion in the beats repo.
